### ISSUE TITLE
Optimization: Overkill composer command in Travis build

### ISSUE THREAD

**Issue by MrPetovan** [paragonie/ionizer#1]
In the `install` part of the Travis configuration:
https://github.com/paragonie/ionizer/blob/e3abcb2aa0b9d4e15cf0b1fac6b395c1e6610e51/.travis.yml#L16-L17
I believe a `composer install` would be enough since the dependencies should already have been computed and committed in the `composer.lock` file beforehand.

It would significantly speed up Travis builds, although the effect is directly dependent on the number of dependencies.

**Comment by paragonie-scott** [comment]
We didn't commit the `composer.lock` file, and I have no intention of doing so.

**Comment by MrPetovan** [comment]
Can I ask you why?

**Comment by paragonie-scott** [comment]
Sure. "Always use the latest version of everything" is a higher priority than "shave a few seconds off Travis runs" in the hierarchy of our development cycle. I also don't want to have to commit updated composer.lock files to 30+ projects and risk overlooking one should a security vulnerability be found in one of our libraries.

**Comment by MrPetovan** [comment]
I see.

The rationale behind the `composer.lock` commit, beyond the time save, is that it prevents sudden incompatibility breaks after a dependency is updated. Of course, as long as you only require your own libraries, I guess this is mitigated.

Beyond that, whether you commit the `composer.lock` or not doesn’t impact your use of `composer update` implied by “Always use the latest version of everything”, but it’s your call, of course.
