### ISSUE TITLE
Philosophy: Does the type check code belong to overloading classes?

### ISSUE THREAD

**Issue by MrPetovan** [paragonie/ionizer#2]
Shouldn't this code:
https://github.com/paragonie/ionizer/blob/e3abcb2aa0b9d4e15cf0b1fac6b395c1e6610e51/src/InputFilter.php#L95-L112
Be moved to the respective `Filter\IntFilter::process()` function?

**Comment by paragonie-scott** [comment]
This was done in https://github.com/paragonie/ionizer/commit/453140ffdf9e3c4878a8fd023dfc71ea24437bea

**Comment by MrPetovan** [comment]
Great!
