### ISSUE TITLE
eval vs dynamic variable

### ISSUE THREAD

**Issue by bubach** [paragonie/ionizer#5]
might be missing something - but shouldn't a dynamic variable in the form `${$var . $append}` let you do that without eval?

https://github.com/paragonie/ionizer/blob/a8329002a8087e4e556757159a7dddc9e942d625/src/InputFilterContainer.php#L78

**Comment by paragonie-security** [comment]
It lets us do _most of _ the work without `eval()`. https://github.com/paragonie/ionizer/commit/5c962261f569ed3d947b174cff3ce10f38072310

The `eval('$filtered =& ' . $var. ';');` remains necessary due to how references work with PHP.
